### PR TITLE
Adding more hosts

### PR DESCRIPTION
**Pull request by danmun**
Added the following hosts
Dropfile.to
ImgSafe.org
Pomf.cat
Biyori.moe

Also, I put all the code responsible for uploading into a new 'uploaders' directory, and changed the file paths accordingly in rehostimage.xul.

Packaged and tested locally.

### CODE REVIEW

**Comment by RandomEngy** [comment]
Wow, looks really awesome. Just one issue: it looks like Dropfile is copying the "container page" URL to the clipboard and not the image itself. Is there any way to get it to copy the direct image so it behaves like the other hosts?

**Comment by danmun** [comment]
I have not found a way to do that. The direct image link doesn't appear in their API response, and it's completely unrelated to the "container" link. I thought about adding a warning message to its GUI panel, that it won't be a direct link, but then didn't. So i can either remove dropfile or add the warning.

**Comment by RandomEngy** [comment]
I think adding a warning would be fine.

**Comment by danmun** [comment]
Now that i think about it, i could get the direct image link but it would require an additional GET after the "container" page link has been fetched.

**Comment by danmun** [comment]
It now copies the direct image URL.
Sorry for the multiple commits, forgot to proof read the code...

**Comment by RandomEngy** [comment]
Alright, merged, built and submitted for review. Thanks for the contribution!

**Pull request merged**
